# Generated by Django 3.2.6 on 2021-08-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='champions',
            fields=[
                ('name', models.CharField(db_index=True, max_length=100)),
                ('id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='durations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimumTime', models.PositiveSmallIntegerField(db_index=True)),
                ('maximumTime', models.PositiveSmallIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='game_modes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('gameId', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('platformId', models.CharField(max_length=100)),
                ('gameCreation', models.PositiveBigIntegerField(db_index=True)),
                ('gameDuration', models.PositiveBigIntegerField(db_index=True)),
                ('queueId', models.PositiveIntegerField(db_index=True)),
                ('mapId', models.PositiveIntegerField(db_index=True)),
                ('seasonId', models.PositiveIntegerField(db_index=True)),
                ('gameVersion', models.CharField(max_length=100)),
                ('gameMode', models.CharField(max_length=100)),
                ('gameType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformId', models.CharField(max_length=100, unique=True)),
                ('regionName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='champion_match_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champLevel', models.PositiveIntegerField(db_index=True)),
                ('win', models.PositiveSmallIntegerField(db_index=True)),
                ('role', models.CharField(max_length=100)),
                ('lane', models.CharField(max_length=100)),
                ('kills', models.PositiveSmallIntegerField()),
                ('deaths', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('pentakills', models.PositiveSmallIntegerField()),
                ('platformId', models.CharField(max_length=100)),
                ('gameMode', models.CharField(max_length=100)),
                ('championId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.matches')),
            ],
        ),
        migrations.CreateModel(
            name='champion_match_bans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.CharField(db_index=True, max_length=100)),
                ('championId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions')),
            ],
        ),
    ]
