# Generated by Django 3.2.6 on 2021-08-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champions',
            name='blurb',
            field=models.TextField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='champions',
            name='info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='champions',
            name='key',
            field=models.CharField(db_index=True, default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='champions',
            name='partype',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='champions',
            name='stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='champions',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='champions',
            name='title',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='champions',
            name='version',
            field=models.CharField(db_index=True, default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='champions',
            name='id',
            field=models.CharField(db_index=True, default='empty', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='champions',
            name='image',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='champions',
            name='name',
            field=models.CharField(db_index=True, default='empty', max_length=100),
        ),
    ]
