# Generated by Django 3.1.2 on 2022-02-18 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_id', models.BigIntegerField()),
                ('filter_value', models.TextField()),
            ],
            options={
                'db_table': 'filter_combinations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='durations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimumTime', models.PositiveSmallIntegerField(db_index=True)),
                ('maximumTime', models.PositiveSmallIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='game_modes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('platformId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='champion_match_bans',
            name='championId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key'),
        ),
        migrations.AddField(
            model_name='champion_match_performance',
            name='championId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key'),
        ),
        migrations.AddField(
            model_name='champion_match_performance',
            name='gameId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.matches'),
        ),
        migrations.AddField(
            model_name='champion_match_performance',
            name='summonerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.summoner'),
        ),
        migrations.AddField(
            model_name='championsummoners',
            name='championid',
            field=models.ForeignKey(db_column='championid', default='', on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key'),
        ),
        migrations.AddField(
            model_name='rune',
            name='pathid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.runepath'),
        ),
        migrations.AddField(
            model_name='runestatistics',
            name='rune_page_id',
            field=models.ForeignKey(db_column='rune_page_id', default='', on_delete=django.db.models.deletion.PROTECT, to='api.runepage'),
        ),
        migrations.CreateModel(
            name='spell_match_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_level', models.CharField(default='', max_length=100)),
                ('champLevel', models.PositiveIntegerField(blank=True, db_index=True)),
                ('win', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(1)])),
                ('gameMode', models.CharField(max_length=100)),
                ('tier_id', models.CharField(max_length=100)),
                ('summoner_id', models.CharField(default='', max_length=100)),
                ('championId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.matches')),
                ('spellId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.spell')),
            ],
        ),
        migrations.CreateModel(
            name='rune_match_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_level', models.PositiveIntegerField(db_index=True)),
                ('champLevel', models.PositiveIntegerField(blank=True, db_index=True)),
                ('win', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(1)])),
                ('gameMode', models.CharField(max_length=100)),
                ('tier_id', models.CharField(max_length=100)),
                ('summoner_id', models.CharField(default='', max_length=100)),
                ('championId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.matches')),
                ('platformId', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.regions')),
                ('runeId', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.rune')),
                ('runepathId', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.runepath')),
                ('summonerId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.summoner', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='item_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=200)),
                ('attribute_value', models.JSONField(blank=True, default=dict)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='item_match_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonerId', models.CharField(max_length=100, null=True)),
                ('tier', models.CharField(max_length=100, null=True)),
                ('win', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(1)])),
                ('gameMode', models.CharField(max_length=100)),
                ('championId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.matches')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.item')),
                ('platformId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.regions')),
            ],
        ),
    ]
