# Generated by Django 3.1.2 on 2022-02-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220218_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion_match_bans',
            name='championId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key'),
        ),
        migrations.AlterField(
            model_name='champion_match_performance',
            name='championId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key'),
        ),
        migrations.AlterField(
            model_name='champion_match_performance',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.matches'),
        ),
        migrations.AlterField(
            model_name='championsummoners',
            name='championid',
            field=models.ForeignKey(db_column='championid', on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key'),
        ),
        migrations.AlterField(
            model_name='rune',
            name='pathid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.runepath'),
        ),
        migrations.AlterField(
            model_name='rune_match_performance',
            name='platformId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.regions'),
        ),
        migrations.AlterField(
            model_name='rune_match_performance',
            name='runeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rune'),
        ),
        migrations.AlterField(
            model_name='rune_match_performance',
            name='runepathId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.runepath'),
        ),
        migrations.AlterField(
            model_name='rune_match_performance',
            name='summonerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.summoner', to_field='name'),
        ),
        migrations.AlterField(
            model_name='runestatistics',
            name='rune_page_id',
            field=models.ForeignKey(db_column='rune_page_id', on_delete=django.db.models.deletion.PROTECT, to='api.runepage'),
        ),
    ]
