# Generated by Django 3.2.6 on 2021-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(db_index=True, default='empty', max_length=200),
        ),
    ]
