# Generated by Django 3.1.2 on 2022-02-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220218_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runepage',
            options={'managed': False},
        ),
    ]
