# Generated by Django 3.2.6 on 2021-08-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210824_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion_match_bans',
            name='championId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key'),
        ),
    ]
