# Generated by Django 3.2.6 on 2021-08-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colloq',
            field=models.CharField(db_index=True, default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='plaintext',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
