# Generated by Django 3.2.6 on 2021-08-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_champion_match_bans_championid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion_match_performance',
            name='pentakills',
            field=models.FloatField(),
        ),
    ]
