# Generated by Django 3.1.2 on 2022-02-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220218_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runepage',
            options={},
        ),
    ]
