# Generated by Django 3.2.6 on 2021-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210825_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gold',
            field=models.JSONField(db_index=True, default=dict),
        ),
    ]
