# Generated by Django 3.1.2 on 2021-08-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210824_1449'),
        ('api', '0006_alter_item_gold'),
    ]

    operations = [
    ]
