# Generated by Django 3.2.6 on 2021-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_champion_match_performance_pentakills'),
        ('api', '0007_merge_20210826_0817'),
    ]

    operations = [
    ]
