# Generated by Django 3.1.2 on 2021-08-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20210827_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='into',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
    ]
