# Generated by Django 3.1.2 on 2021-08-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_item_rune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, default='empty', max_length=200),
        ),
    ]
