# Generated by Django 3.2.6 on 2021-08-30 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210829_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_match_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('picks', models.PositiveSmallIntegerField()),
                ('win', models.PositiveSmallIntegerField(db_index=True)),
                ('gameMode', models.CharField(max_length=100)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.matches')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.item')),
                ('regionId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.regions')),
            ],
        ),
    ]
