# Generated by Django 3.1.2 on 2021-08-30 19:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210829_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.JSONField(default=dict)),
                ('description', models.TextField(default='')),
                ('rune', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None)),
            ],
        ),
    ]
