# Generated by Django 3.2.6 on 2021-08-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_item_match_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_match_performance',
            name='id',
            field=models.CharField(db_index=True, default='empty', max_length=100, primary_key=True, serialize=False),
        ),
    ]
