# Generated by Django 3.1.2 on 2021-08-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rune',
            old_name='description',
            new_name='longDesc',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='rune',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='tags',
        ),
        migrations.AddField(
            model_name='rune',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rune',
            name='key',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rune',
            name='shortDesc',
            field=models.TextField(default=''),
        ),
    ]
