# Generated by Django 3.1.2 on 2021-09-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210831_2011'),
        ('api', '0018_auto_20210901_0940'),
    ]

    operations = [
    ]
