# Generated by Django 3.1.2 on 2021-09-01 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20210901_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunePath',
            fields=[
                ('id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, default='', max_length=200)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('icon', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='rune',
            name='pathid',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.PROTECT, to='api.runepath'),
            preserve_default=False,
        ),
    ]
