# Generated by Django 3.2.6 on 2021-09-01 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210901_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_match_performance',
            name='win',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
