# Generated by Django 3.2.6 on 2021-09-01 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_item_match_performance_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion_match_performance',
            name='win',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
