# Generated by Django 3.2.6 on 2021-09-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210901_2211'),
        ('api', '0021_alter_champion_match_performance_win'),
    ]

    operations = [
    ]
