# Generated by Django 3.2.6 on 2021-09-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20210902_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=200)),
                ('attribute_value', models.CharField(max_length=200)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.item')),
            ],
        ),
    ]
