# Generated by Django 3.1.2 on 2021-09-04 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20210902_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.CharField(db_index=True, default='', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='', max_length=400)),
                ('tooltip', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('maxrank', models.IntegerField(db_index=True)),
                ('cooldown', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('cooldownBurn', models.CharField(default='', max_length=200)),
                ('cost', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('costBurn', models.CharField(default='', max_length=200)),
                ('datavalues', models.JSONField(blank=True, default=dict)),
                ('effect', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None), default=list, null=True, size=None)),
                ('effectBurn', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None)),
                ('vars', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None)),
                ('key', models.CharField(blank=True, default='', max_length=200)),
                ('summonerLevel', models.IntegerField()),
                ('modes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None)),
                ('costType', models.CharField(blank=True, default='', max_length=200)),
                ('maxammo', models.CharField(default='', max_length=200)),
                ('range', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None)),
                ('rangeBurn', models.CharField(max_length=200)),
                ('image', models.JSONField(blank=True, default=dict)),
                ('resource', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
