# Generated by Django 3.2.6 on 2021-09-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_item_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_property',
            name='attribute_value',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
