# Generated by Django 3.1.2 on 2021-09-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_item_property_attribute_value'),
        ('api', '0024_spell_match_performance'),
    ]

    operations = [
    ]
