# Generated by Django 3.2.6 on 2021-09-07 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_item_property_attribute_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='summoner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accountId', models.CharField(max_length=100)),
                ('puuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profileIconId', models.PositiveIntegerField(db_index=True)),
                ('revisionDate', models.DateTimeField(auto_now=True)),
                ('summonerLevel', models.PositiveIntegerField(db_index=True)),
            ],
        ),
    ]
