# Generated by Django 3.1.2 on 2021-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20210907_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell_match_performance',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='spell_match_performance',
            name='pick_rate',
        ),
        migrations.RemoveField(
            model_name='spell_match_performance',
            name='win_rate',
        ),
        migrations.AddField(
            model_name='spell_match_performance',
            name='summoner_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='item_property',
        ),
    ]
