# Generated by Django 3.2.6 on 2021-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_champion_match_performance_tierid'),
    ]

    operations = [
        migrations.CreateModel(
            name='rank',
            fields=[
                ('tierRank', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ranks',
            new_name='tier',
        ),
    ]
