# Generated by Django 3.1.2 on 2021-09-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_spell_match_performance_champlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell_match_performance',
            name='champLevel',
            field=models.PositiveIntegerField(blank=True, db_index=True),
        ),
    ]
