# Generated by Django 3.1.2 on 2021-09-07 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210907_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='rune_match_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_level', models.PositiveIntegerField(db_index=True)),
                ('champLevel', models.PositiveIntegerField(blank=True, db_index=True)),
                ('win', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(1)])),
                ('gameMode', models.CharField(max_length=100)),
                ('tier_id', models.CharField(max_length=100)),
                ('championId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.matches')),
                ('platformId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.regions')),
                ('runeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rune')),
                ('runepathId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.runepath')),
            ],
        ),
    ]
