# Generated by Django 3.2.6 on 2021-09-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_champion_match_performance_participantid"),
    ]

    operations = [
        migrations.AddField(
            model_name="item_match_performance",
            name="participantId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.summoner",
                to_field="name",
            ),
        ),
    ]
