# Generated by Django 3.1.2 on 2021-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rune_match_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rune_match_performance',
            name='summoner_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
