# Generated by Django 3.2.6 on 2021-09-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210907_1806'),
        ('api', '0029_alter_champion_match_performance_participantid'),
    ]

    operations = [
    ]
