# Generated by Django 3.2.6 on 2021-09-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20210907_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion_match_performance',
            old_name='participantId',
            new_name='summonerId',
        ),
    ]
