# Generated by Django 3.2.6 on 2021-09-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_item_match_performance_participantid'),
        ('api', '0031_rename_participantid_champion_match_performance_summonerid'),
    ]

    operations = [
    ]
