# Generated by Django 3.2.6 on 2021-09-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rune_match_performance_summoner_id'),
        ('api', '0033_rename_participantid_item_match_performance_summonerid'),
    ]

    operations = [
    ]
