# Generated by Django 3.1.2 on 2021-09-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_20210908_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=200)),
                ('attribute_value', models.JSONField(blank=True, default=dict)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.item')),
            ],
        ),
    ]
