# Generated by Django 3.2.6 on 2021-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_auto_20210909_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summoner",
            name="id",
            field=models.CharField(
                db_index=True,
                default="empty",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="summoner",
            name="puuid",
            field=models.CharField(db_index=True, default="empty", max_length=100),
        ),
    ]
