# Generated by Django 3.2.6 on 2021-09-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_auto_20210909_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="rune_match_performance",
            name="summonerId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.summoner",
                to_field="name",
            ),
        ),
    ]
