# Generated by Django 3.1.2 on 2021-09-11 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_auto_20210911_0827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spell",
            name="effect",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(blank=True, null=True),
                    null=True,
                    size=None,
                ),
                default=list,
                null=True,
                size=11,
            ),
        ),
    ]
