# Generated by Django 3.2.6 on 2021-09-10 15:46

from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_auto_20210909_1600"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="", max_length=400)),
                (
                    "tooltip",
                    models.TextField(blank=True, default="", max_length=200, null=True),
                ),
                ("maxrank", models.IntegerField(db_index=True)),
                (
                    "cooldown",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                ("cooldownBurn", models.CharField(default="", max_length=200)),
                (
                    "cost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                ("costBurn", models.CharField(default="", max_length=200)),
                ("datavalues", models.JSONField(blank=True, default=dict)),
                (
                    "effect",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.IntegerField(blank=True, null=True),
                            null=True,
                            size=None,
                        ),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "effectBurn",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(null=True),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "vars",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True),
                        default=list,
                        size=None,
                    ),
                ),
                ("key", models.CharField(blank=True, default="", max_length=200)),
                ("summonerLevel", models.IntegerField()),
                (
                    "modes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200),
                        default=list,
                        size=None,
                    ),
                ),
                ("costType", models.CharField(blank=True, default="", max_length=200)),
                ("maxammo", models.CharField(default="", max_length=200)),
                (
                    "range",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True),
                        default=list,
                        size=None,
                    ),
                ),
                ("rangeBurn", models.CharField(max_length=200)),
                ("image", models.JSONField(blank=True, default=dict)),
                ("resource", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="item_match_performance",
            name="category",
        ),
    ]
