# Generated by Django 3.1.2 on 2021-09-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rune_match_performance_summonerid'),
        ('api', '0038_auto_20210911_0829'),
        ('api', '0038_remove_item_match_performance_category'),
    ]

    operations = [
    ]
