# Generated by Django 3.2.6 on 2021-09-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rune_match_performance_summonerid'),
        ('api', '0038_remove_item_match_performance_category'),
    ]

    operations = [
    ]
