# Generated by Django 3.1.2 on 2021-09-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_merge_20210910_1634'),
        ('api', '0040_auto_20210911_0934'),
    ]

    operations = [
    ]
