# Generated by Django 3.1.2 on 2021-09-14 15:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_auto_20210914_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spell",
            name="effectBurn",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200, null=True),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="spell",
            name="id",
            field=models.CharField(db_index=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="spell",
            name="key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
