# Generated by Django 3.1.2 on 2021-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20210914_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionsStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championid', models.IntegerField(blank=True, db_column='championId', null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('tier', models.CharField(blank=True, max_length=100, null=True)),
                ('matchtype', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('fgm', models.CharField(blank=True, db_column='fgm', max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('winrate', models.FloatField(blank=True, null=True)),
                ('banrate', models.FloatField(blank=True, null=True)),
                ('pickrate', models.FloatField(blank=True, null=True)),
                ('mained_by_champid', models.IntegerField(blank=True, db_column='mained_by_champId', null=True)),
                ('mained_by_field', models.FloatField(blank=True, db_column='mained_by', null=True)),
                ('counters_champid', models.IntegerField(blank=True, db_column='counters_champId', null=True)),
                ('counters_field', models.FloatField(blank=True, db_column='counters', null=True)),
                ('is_countered_by_champid', models.IntegerField(blank=True, db_column='is_countered_by_champId', null=True)),
                ('is_countered_by_field', models.FloatField(blank=True, db_column='is_countered_by', null=True)),
                ('boots', models.CharField(blank=True, max_length=100, null=True)),
                ('core_build', models.CharField(blank=True, max_length=100, null=True)),
                ('starting_build', models.CharField(blank=True, max_length=100, null=True)),
                ('end_build', models.CharField(blank=True, max_length=100, null=True)),
                ('kills', models.FloatField(blank=True, null=True)),
                ('deaths', models.FloatField(blank=True, null=True)),
                ('assists', models.FloatField(blank=True, null=True)),
                ('pentakills', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'champions_stats',
                'managed': True,
            },
        ),
    ]
