# Generated by Django 3.1.2 on 2021-10-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_championsstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='spell_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.CharField(blank=True, db_column='spells', max_length=100, null=True)),
                ('championid', models.IntegerField(blank=True, db_column='championId', null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('tier', models.CharField(blank=True, max_length=100, null=True)),
                ('fgm', models.CharField(blank=True, db_column='fgm', max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('winrate', models.FloatField(blank=True, null=True)),
                ('pickrate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spell_stats',
                'managed': True,
            },
        ),
    ]
