# Generated by Django 3.1.2 on 2021-10-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_spell_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='spell_stats',
            new_name='spells_stats',
        ),
    ]
