# Generated by Django 3.1.2 on 2021-10-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20211025_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summoner',
            options={'managed': True},
        ),
    ]
