# Generated by Django 3.1.2 on 2021-11-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20211029_1325'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spells_stats',
            table='spells_stats',
        ),
    ]
