# Generated by Django 3.1.2 on 2021-10-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_auto_20211025_1955"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summoner",
            name="accountId",
        ),
        migrations.RemoveField(
            model_name="summoner",
            name="profileIconId",
        ),
        migrations.RemoveField(
            model_name="summoner",
            name="revisionDate",
        ),
        migrations.RemoveField(
            model_name="summoner",
            name="summonerLevel",
        ),
        migrations.AddField(
            model_name="summoner",
            name="accountid",
            field=models.CharField(default="1", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summoner",
            name="profileiconid",
            field=models.CharField(default="1", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summoner",
            name="region",
            field=models.CharField(default="1", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summoner",
            name="revisiondate",
            field=models.CharField(default="1", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summoner",
            name="summonerlevel",
            field=models.CharField(default="1", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summoner",
            name="tier",
            field=models.CharField(default="1", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="summoner",
            name="id",
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="summoner",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="summoner",
            name="puuid",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterModelTable(
            name="summoner",
            table="summoners",
        ),
    ]
