# Generated by Django 3.1.2 on 2021-10-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20211027_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summoner',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='championsummoners',
        ),
    ]
