# Generated by Django 3.1.2 on 2021-10-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20211027_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='championsummoners',
            name='games_played',
            field=models.IntegerField(db_column='games_played', default=0),
        ),
    ]
