# Generated by Django 3.1.2 on 2021-10-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_spell_stats'),
        ('api', '0054_championsummoners_games_played'),
    ]

    operations = [
    ]
