# Generated by Django 3.1.2 on 2021-11-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_merge_20211028_1243'),
        ('api', '0050_auto_20211101_1336'),
    ]

    operations = [
    ]
