# Generated by Django 3.1.2 on 2021-11-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_merge_20211101_1556'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spells_stats',
            table='spell_stats',
        ),
    ]
