# Generated by Django 3.1.2 on 2021-11-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20211102_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='rune',
            name='slot',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
