# Generated by Django 3.1.2 on 2021-11-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_rune_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells_stats',
            name='championid',
            field=models.CharField(blank=True, db_column='championId', max_length=100, null=True),
        ),
    ]
