# Generated by Django 3.1.2 on 2021-11-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_rune_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunePage',
            fields=[
                ('rune_page_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('primary_style', models.TextField(default='')),
                ('key_stone', models.TextField(default='')),
                ('primary_perk0_1', models.TextField(default='')),
                ('primary_perk0_2', models.TextField(default='')),
                ('primary_perk0_3', models.TextField(default='')),
                ('shard1', models.TextField(default='')),
                ('shard2', models.TextField(default='')),
                ('shard3', models.TextField(default='')),
                ('secondary_style', models.TextField(default='')),
                ('secondary_perk0_1', models.TextField(default='')),
                ('secondary_perk0_2', models.TextField(default='')),
            ],
            options={
                'db_table': 'rune_pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuneStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championId', models.TextField()),
                ('role', models.TextField(null=True)),
                ('region', models.TextField(null=True)),
                ('fgm', models.TextField(null=True)),
                ('tier', models.TextField(null=True)),
                ('duration', models.TextField(null=True)),
                ('winrate', models.FloatField()),
                ('banrate', models.FloatField()),
                ('rune_page_id', models.ForeignKey(db_column='rune_page_id', on_delete=django.db.models.deletion.PROTECT, to='api.runepage')),
            ],
            options={
                'db_table': 'rune_statistics',
            },
        ),
    ]
