# Generated by Django 3.1.2 on 2021-11-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20211103_1549'),
        ('api', '0060_auto_20211103_1533'),
    ]

    operations = [
    ]
