# Generated by Django 3.1.2 on 2021-11-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_merge_20211104_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.TextField(blank=True, null=True)),
                ('championid', models.CharField(blank=True, db_column='championId', max_length=100, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('tier', models.TextField(blank=True, null=True)),
                ('fgm', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('winrate', models.FloatField(blank=True, null=True)),
                ('pickrate', models.FloatField(blank=True, null=True)),
                ('games_played', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spell_stats',
                'managed': False,
            },
        ),
    ]
