# Generated by Django 3.1.2 on 2021-11-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_spellstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.TextField(blank=True, max_length=100, null=True)),
                ('role', models.TextField(blank=True, max_length=100, null=True)),
                ('duration', models.TextField(blank=True, max_length=100, null=True)),
                ('region', models.TextField(blank=True, max_length=100, null=True)),
                ('fgm', models.TextField(blank=True, max_length=100, null=True)),
                ('winrate', models.FloatField(blank=True, null=True)),
                ('pickrate', models.FloatField(blank=True, null=True)),
                ('spell_1_level_1', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_1_level_2', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_1_level_3', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_1_level_4', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_1_level_5', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_2_level_1', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_2_level_2', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_2_level_3', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_2_level_4', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_2_level_5', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_3_level_1', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_3_level_2', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_3_level_3', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_3_level_4', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_3_level_5', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_4_level_1', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_4_level_2', models.TextField(blank=True, max_length=4, null=True)),
                ('spell_4_level_3', models.TextField(blank=True, max_length=4, null=True)),
                ('championId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.champions', to_field='key')),
            ],
        ),
    ]
