# Generated by Django 3.1.2 on 2021-11-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_skillorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='runepath',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
