# Generated by Django 3.1.2 on 2021-11-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_rolestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='championsummoners',
            name='duration',
            field=models.TextField(db_column='gameduration', null=True),
        ),
        migrations.AddField(
            model_name='championsummoners',
            name='fgm',
            field=models.TextField(db_column='gamemode', null=True),
        ),
        migrations.AddField(
            model_name='championsummoners',
            name='role',
            field=models.TextField(db_column='final_role', null=True),
        ),
    ]
