# Generated by Django 3.1.2 on 2021-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20211116_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_id', models.BigIntegerField()),
                ('filter_value', models.TextField()),
            ],
            options={
                'db_table': 'filter_combinations',
                'managed': False,
            },
        ),
    ]
