# Generated by Django 3.1.2 on 2021-11-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20211122_1113'),
        ('api', '0067_filtercombination'),
    ]

    operations = [
    ]
