# Generated by Django 3.1.2 on 2021-11-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_merge_20211122_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championsummoners',
            name='summonername',
            field=models.TextField(),
        ),
    ]
