# Generated by Django 3.1.2 on 2021-11-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_auto_20211126_1248"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChampionSpell",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "champion_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "champion_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("spell_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("image", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "champion_spells",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ItemsStats",
            fields=[
                ("region", models.TextField(blank=True, null=True)),
                ("fgm", models.TextField(blank=True, null=True)),
                ("tier", models.TextField(blank=True, null=True)),
                ("role", models.TextField(blank=True, null=True)),
                ("starter_item", models.TextField(blank=True, null=True)),
                ("early_item", models.TextField(blank=True, null=True)),
                ("winrate", models.FloatField(blank=True, null=True)),
                ("games_played", models.BigIntegerField(blank=True, null=True)),
                ("pickrate", models.FloatField(blank=True, null=True)),
                ("starter_time", models.FloatField(blank=True, null=True)),
                ("early_time", models.FloatField(blank=True, null=True)),
                ("core_time", models.FloatField(blank=True, null=True)),
                ("core_items", models.TextField(blank=True, null=True)),
                ("full_build", models.TextField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "items_stats",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="skillorders",
            name="championId",
        ),
        migrations.AddField(
            model_name="skillorders",
            name="championid",
            field=models.CharField(
                blank=True, db_column="championid", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="skillorders",
            name="games_played",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
