# Generated by Django 3.1.2 on 2021-12-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20211127_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championsstats',
            name='boots',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='core_build',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='counters_champid',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='counters_field',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='end_build',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='is_countered_by_champid',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='is_countered_by_field',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='mained_by_champid',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='mained_by_field',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='matchtype',
        ),
        migrations.RemoveField(
            model_name='championsstats',
            name='starting_build',
        ),
        migrations.AddField(
            model_name='championsstats',
            name='games_played',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
