# Generated by Django 3.1.2 on 2021-12-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20211206_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='rune',
            name='version',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
