# Generated by Django 3.1.2 on 2021-12-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_skillorders_duration'),
        ('api', '0072_rune_version'),
    ]

    operations = [
    ]
