# Generated by Django 3.1.2 on 2021-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_merge_20211217_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='version',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
