data = [
    {
        "pickRate": "11.7",
        "winRate": "42.7",
        "primaryStyle": {
            "name": "Precision",
            "key": "Precision",
            "id": "8000",
            "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/7201_Precision.png",
            "keystones": [
                {
                    "name": "Press the Attack",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/PressTheAttack/PressTheAttack.png",
                    "selected": False,
                    "id": "8005",
                    "key": "PressTheAttack",
                },
                {
                    "name": "Lethal Tempo",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/LethalTempo/LethalTempoTemp.png",
                    "selected": False,
                    "id": "8008",
                    "key": "LethalTempo",
                },
                {
                    "name": "Fleet Footwork",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/FleetFootwork/FleetFootwork.png",
                    "selected": False,
                    "id": "8021",
                    "key": "FleetFootwork",
                },
                {
                    "name": "Conqueror",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Conqueror/Conqueror.png",
                    "selected": True,
                    "id": "8010",
                    "key": "Conqueror",
                },
            ],
            "slot_1": [
                {
                    "name": "Overheal",
                    "key": "Overheal",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Overheal.png",
                    "selected": False,
                    "id": "9101",
                },
                {
                    "name": "Triumph",
                    "key": "Triumph",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Triumph.png",
                    "selected": True,
                    "id": "9111",
                },
                {
                    "name": "Overheal",
                    "key": "Overheal",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/PresenceOfMind/PresenceOfMind.png",
                    "selected": False,
                    "id": "8009",
                },
            ],
            "slot_2": [
                {
                    "name": "Overheal",
                    "key": "Overheal",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Overheal.png",
                    "selected": False,
                    "id": "9101",
                },
                {
                    "name": "Triumph",
                    "key": "Triumph",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Triumph.png",
                    "selected": True,
                    "id": "9111",
                },
                {
                    "name": "Overheal",
                    "key": "Overheal",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/PresenceOfMind/PresenceOfMind.png",
                    "selected": False,
                    "id": "8009",
                },
            ],
            "slot_3": [
                {
                    "name": "Legend: Alacrity",
                    "key": "LegendAlacrity",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/LegendAlacrity/LegendAlacrity.png",
                    "selected": False,
                    "id": "9104",
                },
                {
                    "key": "LegendTenacity",
                    "name": "Legend: Tenacity",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/LegendTenacity/LegendTenacity.png",
                    "selected": True,
                    "id": "9105",
                },
                {
                    "key": "LegendBloodline",
                    "name": "Legend: Bloodline",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/LegendBloodline/LegendBloodline.png",
                    "selected": False,
                    "id": "9103",
                },
            ],
        },
        "subStyle": {
            "name": "Domination",
            "key": "Domination",
            "id": "8100",
            "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/7200_Domination.png",
            "keystones": [
                {
                    "name": "Electrocute",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/Electrocute/Electrocute.png",
                    "selected": False,
                    "id": "8112",
                    "key": "Electrocute",
                },
                {
                    "name": "Predator",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/Predator/Predator.png",
                    "selected": False,
                    "id": "8124",
                    "key": "Predator",
                },
                {
                    "name": "Dark Harvest",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/DarkHarvest/DarkHarvest.png",
                    "selected": False,
                    "id": "8128",
                    "key": "DarkHarvest",
                },
                {
                    "name": "Hail of Blades",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/HailOfBlades/HailOfBlades.png",
                    "selected": False,
                    "id": "9923",
                    "key": "HailOfBlades",
                },
            ],
            "slot_1": [
                {
                    "name": "Cheap Shot",
                    "key": "CheapShot",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/CheapShot/CheapShot.png",
                    "selected": False,
                    "id": "8126",
                },
                {
                    "name": "Taste Of Blood",
                    "key": "TasteOfBlood",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/TasteOfBlood/GreenTerror_TasteOfBlood.png",
                    "selected": True,
                    "id": "8139",
                },
                {
                    "name": "Sudden Impact",
                    "key": "SuddenImpact",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/SuddenImpact/SuddenImpact.png",
                    "selected": False,
                    "id": "8143",
                },
            ],
            "slot_2": [
                {
                    "name": "ZombieWard",
                    "key": "Zombie Ward",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/ZombieWard/ZombieWard.png",
                    "selected": False,
                    "id": "8136",
                },
                {
                    "name": "Ghost Poro",
                    "key": "GhostPoro",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/GhostPoro/GhostPoro.png",
                    "selected": False,
                    "id": "8120",
                },
                {
                    "name": "Eyeball Collection",
                    "key": "EyeballCollection",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/EyeballCollection/EyeballCollection.png",
                    "selected": False,
                    "id": "8138",
                },
            ],
            "slot_3": [
                {
                    "name": "Ravenous Hunter",
                    "key": "RavenousHunter",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/RavenousHunter/RavenousHunter.png",
                    "selected": False,
                    "id": "8135",
                },
                {
                    "name": "IngeniousHunter",
                    "key": "Ingenious Hunter",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/IngeniousHunter/IngeniousHunter.png",
                    "selected": True,
                    "id": "8134",
                },
                {
                    "name": "Relentless Hunter",
                    "key": "RelentlessHunter",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/RelentlessHunter/RelentlessHunter.png",
                    "selected": False,
                    "id": "8105",
                },
                {
                    "name": "Ultimate Hunter",
                    "key": "UltimateHunter",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/UltimateHunter/UltimateHunter.png",
                    "selected": False,
                    "id": "8106",
                },
            ],
        },
        "shards": {
            "defense": [
                {
                    "name": "5.4 bonus Attack Damage or 9 Ability Power (Adaptive)",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsAdaptiveForceIcon.png",
                    "selected": False,
                    "id": "5001",
                },
                {
                    "name": "10% bonus attack speed",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsAttackSpeedIcon.png",
                    "selected": True,
                    "id": "5002",
                },
                {
                    "name": "8 ability haste",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsCDRScalingIcon.png",
                    "selected": False,
                    "id": "5003",
                },
            ],
            "flex": [
                {
                    "name": "5.4 bonus Attack Damage or 9 Ability Power (Adaptive)",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsAdaptiveForceIcon.png",
                    "selected": False,
                    "id": "5004",
                },
                {
                    "name": "6 bonus armor",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsArmorIcon.png",
                    "selected": True,
                    "id": "5005",
                },
                {
                    "name": "8 bonus magic resistance",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsMagicResIcon.png",
                    "selected": False,
                    "id": "5006",
                },
            ],
            "offense": [
                {
                    "name": "5.4 bonus Attack Damage or 9 Ability Power (Adaptive)",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsAdaptiveForceIcon.png",
                    "selected": True,
                    "id": "5007",
                },
                {
                    "name": "6 bonus armor",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsArmorIcon.png",
                    "selected": False,
                    "id": "5008",
                },
                {
                    "name": "15 − 90 (based on level) bonus health",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsMagicResIcon.png",
                    "selected": False,
                    "id": "5009",
                },
            ],
        },
    },
    {
        "pickRate": "11.7",
        "winRate": "42.7",
        "primaryStyle": {
            "name": "Precision",
            "key": "Precision",
            "id": "8000",
            "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/7201_Precision.png",
            "keystones": [
                {
                    "name": "Press the Attack",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/PressTheAttack/PressTheAttack.png",
                    "selected": False,
                    "id": "8005",
                    "key": "PressTheAttack",
                },
                {
                    "name": "Lethal Tempo",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/LethalTempo/LethalTempoTemp.png",
                    "selected": False,
                    "id": "8008",
                    "key": "LethalTempo",
                },
                {
                    "name": "Fleet Footwork",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/FleetFootwork/FleetFootwork.png",
                    "selected": False,
                    "id": "8021",
                    "key": "FleetFootwork",
                },
                {
                    "name": "Conqueror",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Conqueror/Conqueror.png",
                    "selected": True,
                    "id": "8010",
                    "key": "Conqueror",
                },
            ],
            "slot_1": [
                {
                    "name": "Overheal",
                    "key": "Overheal",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Overheal.png",
                    "selected": False,
                    "id": "9101",
                },
                {
                    "name": "Triumph",
                    "key": "Triumph",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Triumph.png",
                    "selected": True,
                    "id": "9111",
                },
                {
                    "name": "Overheal",
                    "key": "Overheal",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/PresenceOfMind/PresenceOfMind.png",
                    "selected": False,
                    "id": "8009",
                },
            ],
            "slot_2": [
                {
                    "name": "Overheal",
                    "key": "Overheal",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Overheal.png",
                    "selected": False,
                    "id": "9101",
                },
                {
                    "name": "Triumph",
                    "key": "Triumph",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/Triumph.png",
                    "selected": True,
                    "id": "9111",
                },
                {
                    "name": "Overheal",
                    "key": "Overheal",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/PresenceOfMind/PresenceOfMind.png",
                    "selected": False,
                    "id": "8009",
                },
            ],
            "slot_3": [
                {
                    "name": "Legend: Alacrity",
                    "key": "LegendAlacrity",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/LegendAlacrity/LegendAlacrity.png",
                    "selected": False,
                    "id": "9104",
                },
                {
                    "key": "LegendTenacity",
                    "name": "Legend: Tenacity",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/LegendTenacity/LegendTenacity.png",
                    "selected": True,
                    "id": "9105",
                },
                {
                    "key": "LegendBloodline",
                    "name": "Legend: Bloodline",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Precision/LegendBloodline/LegendBloodline.png",
                    "selected": False,
                    "id": "9103",
                },
            ],
        },
        "subStyle": {
            "name": "Domination",
            "key": "Domination",
            "id": "8100",
            "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/7200_Domination.png",
            "keystones": [
                {
                    "name": "Electrocute",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/Electrocute/Electrocute.png",
                    "selected": False,
                    "id": "8112",
                    "key": "Electrocute",
                },
                {
                    "name": "Predator",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/Predator/Predator.png",
                    "selected": False,
                    "id": "8124",
                    "key": "Predator",
                },
                {
                    "name": "Dark Harvest",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/DarkHarvest/DarkHarvest.png",
                    "selected": False,
                    "id": "8128",
                    "key": "DarkHarvest",
                },
                {
                    "name": "Hail of Blades",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/HailOfBlades/HailOfBlades.png",
                    "selected": False,
                    "id": "9923",
                    "key": "HailOfBlades",
                },
            ],
            "slot_1": [
                {
                    "name": "Cheap Shot",
                    "key": "CheapShot",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/CheapShot/CheapShot.png",
                    "selected": False,
                    "id": "8126",
                },
                {
                    "name": "Taste Of Blood",
                    "key": "TasteOfBlood",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/TasteOfBlood/GreenTerror_TasteOfBlood.png",
                    "selected": True,
                    "id": "8139",
                },
                {
                    "name": "Sudden Impact",
                    "key": "SuddenImpact",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/SuddenImpact/SuddenImpact.png",
                    "selected": False,
                    "id": "8143",
                },
            ],
            "slot_2": [
                {
                    "name": "ZombieWard",
                    "key": "Zombie Ward",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/ZombieWard/ZombieWard.png",
                    "selected": False,
                    "id": "8136",
                },
                {
                    "name": "Ghost Poro",
                    "key": "GhostPoro",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/GhostPoro/GhostPoro.png",
                    "selected": False,
                    "id": "8120",
                },
                {
                    "name": "Eyeball Collection",
                    "key": "EyeballCollection",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/EyeballCollection/EyeballCollection.png",
                    "selected": False,
                    "id": "8138",
                },
            ],
            "slot_3": [
                {
                    "name": "Ravenous Hunter",
                    "key": "RavenousHunter",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/RavenousHunter/RavenousHunter.png",
                    "selected": False,
                    "id": "8135",
                },
                {
                    "name": "IngeniousHunter",
                    "key": "Ingenious Hunter",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/IngeniousHunter/IngeniousHunter.png",
                    "selected": True,
                    "id": "8134",
                },
                {
                    "name": "Relentless Hunter",
                    "key": "RelentlessHunter",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/RelentlessHunter/RelentlessHunter.png",
                    "selected": False,
                    "id": "8105",
                },
                {
                    "name": "Ultimate Hunter",
                    "key": "UltimateHunter",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/Styles/Domination/UltimateHunter/UltimateHunter.png",
                    "selected": False,
                    "id": "8106",
                },
            ],
        },
        "shards": {
            "defense": [
                {
                    "name": "5.4 bonus Attack Damage or 9 Ability Power (Adaptive)",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsAdaptiveForceIcon.png",
                    "selected": False,
                    "id": "5001",
                },
                {
                    "name": "10% bonus attack speed",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsAttackSpeedIcon.png",
                    "selected": True,
                    "id": "5002",
                },
                {
                    "name": "8 ability haste",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsCDRScalingIcon.png",
                    "selected": False,
                    "id": "5003",
                },
            ],
            "flex": [
                {
                    "name": "5.4 bonus Attack Damage or 9 Ability Power (Adaptive)",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsAdaptiveForceIcon.png",
                    "selected": False,
                    "id": "5004",
                },
                {
                    "name": "6 bonus armor",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsArmorIcon.png",
                    "selected": True,
                    "id": "5005",
                },
                {
                    "name": "8 bonus magic resistance",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsMagicResIcon.png",
                    "selected": False,
                    "id": "5006",
                },
            ],
            "offense": [
                {
                    "name": "5.4 bonus Attack Damage or 9 Ability Power (Adaptive)",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsAdaptiveForceIcon.png",
                    "selected": True,
                    "id": "5007",
                },
                {
                    "name": "6 bonus armor",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsArmorIcon.png",
                    "selected": False,
                    "id": "5008",
                },
                {
                    "name": "15 − 90 (based on level) bonus health",
                    "icon": "https://earlygamestore.z13.web.core.windows.net/dragontail/img/perk-images/StatMods/StatModsMagicResIcon.png",
                    "selected": False,
                    "id": "5009",
                },
            ],
        },
    },
]
